### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by DerMattinger** [EndlesNights/TorchSlab#16]
Similar to Issue #14 

Version 1.6.9 works on the modpack, but the update 1.6.10 causes this crash.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/13/20 9:29 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at com.endlesnights.torchslabsmod.blocks.vanilla.ColorHandler.registerBlockColorHandler(ColorHandler.java:112) ~[?:v1.6.10] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_32_ColorHandler_registerBlockColorHandler_Block.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$3113/365999192.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.87.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$471/502386384.call(Unknown Source) [forge-1.15.2-31.1.87.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at com.endlesnights.torchslabsmod.blocks.vanilla.ColorHandler.registerBlockColorHandler(ColorHandler.java:112)
	at net.minecraftforge.eventbus.ASMEventHandler_32_ColorHandler_registerBlockColorHandler_Block.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$3113/365999192.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$471/502386384.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1805469120 bytes (1721 MB) / 2675965952 bytes (2552 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.87.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.15.2_HD_U_G1_pre15_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.87.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.87
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		forge-1.15.2-31.1.87-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 LOAD_REGISTRIES}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 LOAD_REGISTRIES}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 LOAD_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 LOAD_REGISTRIES}
		torchslabmod-1.15.2_v1.6.10.jar Torch Slab Mod {torchslabmod@1.6.10 ERROR}
		pamhc2trees-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version LOAD_REGISTRIES}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 LOAD_REGISTRIES}
		pamhc2crops-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version LOAD_REGISTRIES}
		treeharvester_1.15-1.0.jar Tree Harvester {treeharvester@1.0 LOAD_REGISTRIES}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 LOAD_REGISTRIES}
		spiderspwebs_1.15.2-1.0.jar Spiders Produce Webs {spiderspwebs@1.0 LOAD_REGISTRIES}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 LOAD_REGISTRIES}
		fablibrary-1.15.2-1.1.jar FAB Library {fablibrary@1.1 LOAD_REGISTRIES}
		Xaeros_Minimap_20.9.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.9.0 LOAD_REGISTRIES}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 LOAD_REGISTRIES}
		PeacefulSurface-1.15.2-v2b.jar PeacefulSurface {peacefulsurface@1.15.2-v2b LOAD_REGISTRIES}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 LOAD_REGISTRIES}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version LOAD_REGISTRIES}
		gravestone-1.17.4.jar Gravestone Mod {gravestone@1.17.4 LOAD_REGISTRIES}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 LOAD_REGISTRIES}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 LOAD_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 LOAD_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 LOAD_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 LOAD_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.69-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.69 LOAD_REGISTRIES}
		DoubleSlabs-1.15-2.2.7.jar Double Slabs {doubleslabs@2.2.7 LOAD_REGISTRIES}
		AmbientEnvironment-3.0.0.jar Ambient Environment {ambientenvironment@3.0.0 LOAD_REGISTRIES}
		nhacampfire_1.15-2.1.jar No Hostiles Around Campfire {nhacampfire@2.1 LOAD_REGISTRIES}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version LOAD_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 LOAD_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version LOAD_REGISTRIES}
		SnowRealMagic-1.15.2-1.8.0.jar Snow! Real Magic! {snowrealmagic@1.8.0 LOAD_REGISTRIES}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 LOAD_REGISTRIES}
		snowbfrmobs_1.15.2-1.0.jar Snowballs Freeze Mobs {snowbfrmobs@1.0 LOAD_REGISTRIES}
		forge-1.15.2-31.1.87-universal.jar Forge {forge@31.1.87 LOAD_REGISTRIES}
		Bountiful-1.15.2-3.1.1.jar Bountiful {bountiful@1.15.2-3.1.1 LOAD_REGISTRIES}
		Quark-r2.1-236.jar Quark {quark@r2.1-236 LOAD_REGISTRIES}
		w2w-1.15.2-0.0.0.1.jar w2w {w2w@NONE LOAD_REGISTRIES}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 LOAD_REGISTRIES}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 LOAD_REGISTRIES}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Launched Version: forge-31.1.87
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre15
	OptiFine Build: 20200503-125846
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by EndlesNights** [comment]
Seems to be running into some issue with kiwi. Will investigate further.

**Comment by Notme2222** [comment]
Having the same issue with the mod

**Comment by BedrockLegends** [comment]
Having the same issues

**Comment by BedrockLegends** [comment]
@EndlesNights _ removed Kiwi and it still crashed

**Comment by winnetrie83** [comment]
I came here to report the same crash.
Here is the crashlog: https://pastebin.com/3z5p0S9b
No crash happens with this mod alone installed.
I have made a custom modpack.
It only crashes with the latest version of this mod : **Torch Slab Mod mc 1.15.2 v1.6.10**
Previous versions do not crash the game
So it's pretty sure a mod incompatibility with something you changed in your latest version.
I haven't found out yet wich mod conflicts with yours and it's definitely an issue with your latest version because older versions do not crash my custom modpack
I also use the latest forge version: **forge-31.2.0**

**Comment by winnetrie83** [comment]
I doesn't crash with Valhelsia modpack, so that will make it more easy to find the incompatible mod

**Comment by winnetrie83** [comment]
I found the wich mod causes issues with your mod. It is Quark

I have forge-31.2.0,  AutoRegLib-1.5-40.jar and Quark-r2.1-237.jar
installed, nothing more. It crashes too.
Here is a crash log with this setup : https://pastebin.com/tav7gEX9

EDIT: Well did some more testing and research and It is related to the newer forge versions AND Quark.

Valhelsia modpack has both your mod(up to date) and Quark (also up to date) but runs forge : **forge-31.1.87**
This setup works fine and no crashes. I hope this is enough information.
I will ofcourse report this to Quark too:

https://github.com/Vazkii/Quark/issues/2162

**Comment by EndlesNights** [comment]
Sorry for my absence, long story short my OS died and it took me a while to rebuild and recover. Now to fixing this mod. I've gone about updating the comparability with Quark, Bees and Upgrade Aquatic. And I've still getting compatibility issues in my tests while attempting to launch with Kiwi based mods along side Quark or  Upgrade Aquatic . 
The issue seems to that my blocks and events which are dependent on Quark/UA are now being registered first. Which they can't do because they require information from from Quark/UA. Thus causing a crash.
When I disable Kiwi & leave in  Quark/UA, everything loads in the right order and works fine.
When I disable Quark/UA and leave in Kiwi & Kiwi mods, no issues occur because no attempt is made to load the Quark and UA dependent blocks.

The only changes between 6.9 to 6.10 was the introduction of support to  Quark/UA, where this error seems to be. The easy stop gap fix for will be an added Try Catch that doges out of attempting to load the comparability if an error occurs. Which will allow for users to still use the basic mod.

**Comment by winnetrie83** [comment]
You know you can control when your mod is loaded? You to define that in your dependencies. Something like: after:quark

Not sure if this is still the same for 1.15+, but what i usually do is the following: `
@Mod(modid = References.MOD_ID, name = References.NAME, version = References.VERSION, dependencies=References.DEPENDENCIES)`

I have here a class References where i have all my references, but that's not required ofc. The important thing here for you is `dependencies=.....` here you can define for example if your mod needs to load before or after 1 or more other mods. Example : 
`dependencies=after:quark`
You can also add multiple separated with a `;`
