### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EternalOne11** [EndlesNights/TorchSlab#17]
I keep getting something like this [16May2020 00:55:25.073] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2074/72600191.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$474/1861622992.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[16May2020 00:55:25.679] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.endlesnights.torchslabsmod.blocks.vanilla.ColorHandler registerBlockColorHandler(Lnet/minecraftforge/client/event/ColorHandlerEvent$Block;)V
|
I think it has something to do with either mixed slabs or the new minecraft abnromal update that came out 3 hours ago.

**Comment by EndlesNights** [comment]
That was part of it. UA changed some of there internal names.  But some other comparability issues popped up with some unrelated APIs. Uploaded a new version that should be able to avoid most comparability crash from now on.
