### ISSUE TITLE
Crash at IME processing

### ISSUE THREAD

**Issue by VladimirMangos** [EndlesNights/TorchSlab#18]
Crash at start in 1.15.2 v1.6.10 but load fine in 1.15.2 v1.6.9

`[14:49:33] [modloading-worker-0/ERROR]: Caught exception during event InterModEnqueueEvent dispatch for modid torchslabmod
java.lang.NoSuchFieldError: JELLY_TORCH_PINK
	at com.endlesnights.torchslabsmod.blocks.upgradeaquatic.UACompat.registerPlaceEntries(UACompat.java:90) ~[?:v1.6.10]
	at com.endlesnights.torchslabsmod.TorchSlabsMod.onInterModEnqueue(TorchSlabsMod.java:84) ~[?:v1.6.10]
	at net.minecraftforge.eventbus.ASMEventHandler_429_TorchSlabsMod_onInterModEnqueue_InterModEnqueueEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2306/1726118601.accept(Unknown Source) [?:31.1]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2288/343016386.accept(Unknown Source) [?:1.8.0_51]
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51]
	at java.util.function.Consumer$$Lambda$2288/343016386.accept(Unknown Source) [?:1.8.0_51]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2573/1272687664.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
`

**Comment by EndlesNights** [comment]
Upgrade just had an update that changed their internal names. Just launched an update that should fix the issue.

**Comment by VladimirMangos** [comment]
Now it crash (TorchSlab marked as error loaded in table)
When I remove affected mod client crash at next mod with same NullPointer error and mark in table about problem loading TorchSlab
[crash-2020-05-18_09.49.59-client.txt](https://github.com/EndlesNights/TorchSlab/files/4642475/crash-2020-05-18_09.49.59-client.txt)
