### ISSUE TITLE
Torchslab Mod 1.6 Update Server Crash

### ISSUE THREAD

**Issue by SerCiddy** [EndlesNights/TorchSlab#7]
Updating 1.15.2 Server running forge 31.1.24 from torchslab 1.5 to torchslab 1.6 causes crash. Here is the full log, error at the bottom. https://pastebin.com/8qkDCAgs

Relevant portion: 
[23Mar2020 09:48:46.141] [Server thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found
[23Mar2020 09:48:46.141] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Torch Slab Mod (torchslabmod) encountered an error during the load_registries event phase
§7Registry Object not present
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:189) ~[?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:967) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:189) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[23Mar2020 09:48:46.151] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to:

**Comment by SissyTrashQueen** [comment]
MC version; 1.15.2
Forge version: 31.1.26

Same crash here: [Extract from the latest.log](https://hastebin.com/yutiqeqeja.sql)
[Crash report](https://hastebin.com/iyiharesoq.rb)
It's a compat issue i guess, loading the mod alone works fine.

**Comment by EndlesNights** [comment]
I made a reference to a mod outside of where it should have been. Try out 1.6.1 patch it should run smoothly now. Sorry about that.

**Comment by SissyTrashQueen** [comment]
That's the one I'm using (torchslabmod-1.15.1_v1.6.jar Torch Slab Mod {torchslabmod@1.6.1 ERROR})
It's difficult to see in the big modlist, but it's there in the crash report

**Comment by EndlesNights** [comment]
Hmm I'm really not sure at the moment. As I'm unable to reproduce the crash issue on my own system. I'm able to load and run the mod on its own and with a dozen other mods without issue at the moment. 
Slard3 your getting a null RegistryObject from a reference I'm making to the buzzierbees Objects. This implies that the BuzzieBee block is not  yet initialised? But in order to get into this class BuzzierBeesCompat, a check is run to see if the BuzzieBee  is loaded: `if(ModList.get().isLoaded("buzzierbees")`

**Comment by EndlesNights** [comment]
Here is an internal test build where I removed the references during the initialisation phase and instead make them at run time. If this still doesn't fix your issue, do you think you could provide me with a link to your modpack please?
[torchslabmod-1.15.1_v1.6.3_TEST.zip](https://github.com/EndlesNights/TorchSlab/files/4389432/torchslabmod-1.15.1_v1.6.3_TEST.zip)

**Comment by slard3** [comment]
That test build isn't starting it seems

![2020-03-26_22 59 48](https://user-images.githubusercontent.com/55768134/77713611-8affb900-6fb5-11ea-87b2-fb3d45bac7ff.png)

**Comment by SissyTrashQueen** [comment]
The test build does work! 😄
![2020-03-26_23 12 45](https://user-images.githubusercontent.com/55768134/77714283-60aefb00-6fb7-11ea-9fdf-b2dc3d4818a7.png)

**Comment by EndlesNights** [comment]
Wait really? So it's running with your whole pack? Well that's great to hear.
